### ISSUE TITLE
Fatal error vid för många produktalternativ

### ISSUE THREAD

**Issue by taggsladder** [PaysonAB/PaysonCheckout2-Opencart-2-0#2]
Behöver undersöka noggrannare. återkommer

**Comment by taggsladder** [comment]
Var stressad och min förra kommentar var lite för mkt vilda västern. Har undersökt det nu i en helt fräsch installation.

Opencart 2.3.0.2

Skapa en produkt enligt bilden med EXAKT samma produktnamn och de tillvalen med EXAKT samma namn så blir det fatal error i kassan. Ändrar man produktnamnet från "äaaa bbbb cccc dddd eeee fff" till "aaaa bbbb cccc dddd eeee fff" så fungerar det t. ex. men har inte hittat mönstret helt...

![fataal_error](https://user-images.githubusercontent.com/41002015/42496829-94df5c6c-8427-11e8-9a5d-01f50f38132c.png)

**Comment by taggsladder** [comment]
Pallar inte vänta.

Felet är rad 408 i "paysonCheckout2.php":

$productTitle = (strlen($productTitle) > 80 ? substr($productTitle, 0, strpos($productTitle, ' ', 80)) : $productTitle);

Mer exakt:
substr($productTitle, 0, strpos($productTitle, ' ', 80))

Där ni letar efter mellanslag i strängen EFTER 80 tecken. I vissa fall som i exemplet ovan där strängen blir längre än 80 tecken men det finns inget mellanslag efter 80 tecken så subtr returnerar FALSE och $productTitle blir tom.

Quickfix:
$productTitle = (strlen($productTitle) > 80 ? mb_strimwidth($productTitle, 0, 80, "...") : $productTitle);

Ej testat fullt men tycks fungera.

**Comment by PaysonAB** [comment]
Det ser korrekt ut, vi ser till att det kommer med i nästa uppdatering.

**Comment by oscar-vil** [comment]
Hej,

Tack för feedback!

Vi kunden tyvärr inte återskapa felet.
Vi är jättetacksamma om du skickar mer detaljer om problemet.
Här hittar du mejladressen till integration: integration@payson.se.

Med vänlig hälsning
Oscar V
Payson AB | integration
